-- phpMyAdmin SQL Dump
-- version 4.1.4
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Aug 14, 2015 at 12:22 PM
-- Server version: 5.6.15-log
-- PHP Version: 5.4.24

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `pitanja`
--

-- --------------------------------------------------------

--
-- Table structure for table `answers`
--

CREATE TABLE IF NOT EXISTS `answers` (
  `id` int(12) NOT NULL AUTO_INCREMENT,
  `answer` varchar(512) COLLATE cp1250_croatian_ci NOT NULL,
  `value` int(5) NOT NULL,
  `tips` varchar(65000) COLLATE cp1250_croatian_ci NOT NULL,
  `question_id` int(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=cp1250 COLLATE=cp1250_croatian_ci AUTO_INCREMENT=67 ;

--
-- Dumping data for table `answers`
--

INSERT INTO `answers` (`id`, `answer`, `value`, `tips`, `question_id`) VALUES
(1, 'I''m a huge fan of the Yankees and avid softball player with the gift of gab; I''m usually the life of the party and fun to hang aroundâ€¦', 25, 'There is no need to discuss spouses, partners, children, or any other strictly personal information.', 1),
(2, 'I consider myself a good listener who can usually read people well, at my last job retention rate of my hires was 20 percent above the department average.', 50, 'Be ready to share three or four of the personal qualities, skills and/or areas of expertise which would help you to excel in the job for which you are interviewing. Ultimately, you will want to share several other strengths before the interview is over.', 1),
(3, 'I am a seasoned Retail Manager strong in developing training programs and loss prevention techniques that have resulted in huge revenue savings for my last employer. In my free time I hold lectures at local community...', 75, 'Hiring manager already has your resume, so they also want to know a little more about you.', 1),
(4, 'Well I am creative, dependable, efficient, enthusiastic, motivated and open minded individual. I also feel that my communication skills are top notch. ', 25, '<b>Think Quality, Not Quantity</b><br>\r\nDon''t just list a bunch of nice adjectives to describe yourself. Sure, you want to sell yourself as the right man or woman for the job, but you''re going to be much more compelling if you cut the buzzwords and speak genuinely about your strengths.', 2),
(5, 'I have an extremely strong work ethic. I prefer to complete the project well ahead of schedule. Last year, I even earned a bonus for completing my three most recent reports one week ahead of time.', 50, '<b>Back Strengths Up With Stories</b><br>\r\nThat said, what''s more important than the strengths you choose is being able to back up your claims-don''t just expect the interviewer to believe you without some evidence. Start off by answering the question directly, and then segue into a story that shows off your skills.', 2),
(6, 'I pride myself on my customer service skills and my ability to resolve what could be difficult situations. With five years of experience as a customer service associate, I have learned to effectively understand and resolve customer issues. My research showed that one of your customers is "XXX" which I already met on my previous job.', 75, '<b>Mention specific opportunity skills</b><br>\r\nDon''t forget your skills that apply specifically to this opportunity, like your experience with or education in:<br>\r\n<ul>\r\n<li>A type of customer</li>\r\n<li>A type of business</li>\r\n<li>An aspect of business (marketing, finance, law, and so on)</li>\r\n<li>A skill (writing great blog posts, selling a specific product, writing great proposals, designing excellent products, etc.)</li>\r\n<li>A technology (OS10, Bluetooth, AWS, CISSP, and so on)</li>\r\n</ul><br>\r\nDon''t limit yourself to the skills you have developed only in school or in a job. You may have also developed skills in any volunteering you may have done, too.', 2),
(7, 'Honestly I don''t have any weakness that would compromise my efficiency.', 25, '<b>Yes, You Do Have a Weakness!</b><br>\r\nThe employer is trying to figure out if your weakness will make it hard for you to do a good job or fit into the organization. They are also interested in how you handle a tough question like this one', 3),
(8, 'I tend to lose my patience with incompetent people. Also, sometimes I have trouble getting up in the morning and getting to work on time. ', 50, '<b>Don''t be too honest.</b><br>\r\nAnother mistake is to be too candid and confess to a weakness that would hinder your ability to excel in the role. Don''t let your real weakness be "too honest"?.', 3),
(9, 'I used to wait until the last minute to set appointments for the coming week, but I realized     that scheduling in advance makes much more sense.', 75, '<b>The smart two-part answer: confession and recovery. Turn a negative into a positive.</b><br>\r\n<b>The confession</b> of the weakness, and...<br>\r\n<b>The recovery</b> - how you manage yourself to minimize the impact of the weakness, or the plan you have for recovery.\r\nBe sure to present these weaknesses in terms of how they impact the employer. \r\n', 3),
(10, 'I have no idea who you are competing with for this particular job so I can''t answer this question with certainty. Feel free to cross-reference my resume with others.', 25, '<b>What makes you the best candidate for this job?</b><br>\r\nIn most cases, you will have no idea who you are competing with for a particular job, so this type of question is really an invitation to summarize your strengths as a candidate with an emphasis on any assets that might separate you from the typical applicant.', 4),
(11, 'I am sure there are lots of talented people applying for such a position. However, given my unique background and experiences, I think I would be a strong candidate for this position', 50, '<b>Make a List of the Priority Job Requirements</b><br>\r\nStart preparing by analyzing the requirements for the job that seem to have the highest priority.  A detailed job description within the listing for the position will give you some cues about what the organization values most from candidates. ', 4),
(12, 'Of course, I am not aware of the other candidates but I created complex Excel macros to track seasonal variations in sales and expenses. I believe I could do something similar with your systems.', 75, '<b>Try to add a strength that is relatively unique, and would add value</b><br>\r\nFor example, although foreign language skills might not be listed in the job advertisement, you might mention that your Spanish language skills would enable you to establish rapport with Spanish-speaking clients.', 4),
(13, 'I am looking for a position that would improve my writing, media relations, event planning skills, and public relations expertise but your salary in accounting is much more attractive.', 25, '<b>Avoid superficial goals as your primary answer.</b><br>\r\nThis type of question presents some potential pitfalls for candidates if they are not careful. Avoid answers that place emphasis on salary, location, and even the company, since employers typically want a candidate who is well qualified for and motivated to pursue the job itself.', 5),
(14, 'This position fits that for me because it''s a growth role that will benefit me professionally because I''m going to be able to learn and develop more skills.', 50, '<b>Consider Why You Want the Job</b><br>\r\nBefore the interview, think carefully about your career aspirations. Then, reread the job listing, and think of ways in which the requirements and responsibilities of the job will prepare you for those goals. You will need to make a strong case for what appeals to you about the job for which you are interviewing, while also addressing your future aspirations', 5),
(15, 'I plan to add value in this position, develop my skills to help grow the company, and eventually move into roles of greater responsibility.', 75, '<b>Explain why this particular job would help you develop.</b><br>\r\nIf you have a general end destination in mind, that''s great. Talk about how this job is going to help you meet that goal. But only in the most general terms.', 5),
(16, 'Stress is not the issue for me. I am a very calm person by nature and I don''t get stressed at all.', 25, '<b>Desired answer to this question is not "I do not get stressed".</b><br>\r\nEveryone feels pressure and stress, the interviewing person or panel wants to know your approach to the inevitable feelings that come with most jobs at some point or another.', 6),
(17, 'At my last job I used to walk the line with deadlines which caused me a lot of stress. I learned not to worry about too much.', 50, '<b>Avoid mentioning a situation when you put yourself in a needlessly stressful situation.</b><br>\r\nIgnoring stress is not a stress-relieving method. ', 6),
(18, 'Yes, I manage pressure very well.  When I work under pressure, I tend to be focused and motivated. \r\nOn my last job stress was very common, but I learned to turn it into a boost.', 75, '<b>Show that stressful conditions will be a motivator for you to thrive and give examples.</b>', 6),
(19, 'My spouse and I are looking for a larger home, and the only way we can afford it is if I start making more money.', 25, '<b>Whatever you do, don''t say it''s money.</b><br>\r\nOne surefire way to abort an otherwise flowing conversation is to say your biggest motivator is money. Compensation is important to everyone, but making it your number one focus will turn off employers. Address the bigger picture of your career fulfillment.', 7),
(20, 'I''m motivated by personal achievements, I like to work hard and achieve the goals that I set out for myself. That keeps me going and motivate me to do more.', 50, '<b>Avoid generalized responses.</b><br>\r\nBe careful about supplying cliche answers, they are easy to detect. You will be best served in the short and long term if you present your genuine "self" and interests in the interview.', 7),
(21, 'I have always wanted to ensure that my company''s clients get the best customer service I can provide. My drive to constantly develop my customer service skills is the reason I earned top sales at my company two quarters in a row.', 75, '<b>Tie in your successes.</b><br>\r\nYour best answer will emphasize that the quality of the position and its tasks/responsibilities, along with the quality of the organization have always been your best motivators. Also, nothing beats and example - on this and any question.', 7),
(22, 'My boss always tent to nag about me going home early. He just didn''t understand my focus issues.', 25, '<b>Don''t panic and rush the response.</b><br>\r\nIf you did not prepare an answer for this question it can lead the interview in unwanted direction. Don''t be too honest. If you recall a situation where your previous boss was yelling at you for coming to business meeting in shorts - don''t mention it.', 8),
(23, 'Well, since I always double-checked my reports my performance was never an issue. You can verify that information with my previous manager, he''ll be happy to respond.', 50, '<b>Perfectionist answer.</b><br>\r\nYou may be surprised that this is considered a valid answer. If you are in the unusual situation where your performance reviews have been flawless, then you can mention that fact and even offer to provide evidence of your stellar reviews.', 8),
(24, 'I try to see criticism as an opportunity to improve my work.  I was once asked to make a presentation for the entire team and my superiors were not impressed by it. I was open minded about their criticism and became really good presenter after that. ', 75, '<b>The good old confession and recovery.</b><br>\r\nConstructive criticism is an important part of professional growth, and this is a good chance to show your employer you are striving to be the best and are open to improvement. Share and experience from your previous job and explain how it helped you become a better employee.', 8),
(25, 'This job is definitely something I''ve been dreaming about for a long time. I will be perfectly happy if I get this position.', 25, '<b>Don''t Undersell Yourself</b><br>\r\nDon''t say your dream job is the one you''re applying for, or even the one above that. While a business will want someone who''s happy doing the job they''re being hired for, they also want someone with drive and ambition â€“ and this must be demonstrated in the interview.', 9),
(26, 'My dream job would be Head of Department of Google or Microsoft. I know it sounds ambitious but my sheer confidence if my key strength.', 50, '<b>Avoid Mentioning Job Titles</b><br>\r\nSaying you want to be CEO or Head of Department during an interview can set you step back in the interview. Instead focus on job responsibilities that you would enjoy carrying out, skills you''d like to develop and passions you''d enjoy making the most of in day-to-day working life.', 9),
(27, 'What I look for in a job is the ability to utilize my communication and customer service skills. Ultimately, I would like to work in public relations department and this job would be my first step towards it.', 75, '<b>Focus on the Present and the Future</b><br>\r\nMention a certain goal you would like to reach through your dream job? Ultimately, the key to is to convey your long-term interest in a high-level position, without overshadowing your interest in the job you''re applying for.', 9),
(28, 'What really gets me is when people don''t know how to do their work. I get the urge to kick them out myself.', 25, '<b>If you have anger problems, attend them before coming to interview.</b><br>\r\nInterviewer is trying to determine how you might react to stressful situations in the workplace, and how you might handle your personal emotions without letting them affect your performance. If anger is really a problem you may not be suited for the position.', 10),
(29, 'My previous employer did not grant me bonus for my extra work. We ended up in loud discussion but managed to resolve it in mutual benefit.', 50, '<b>Avoid bringing up a situation that involves a supervisor</b><br>\r\nEmployers tend to side with management and may perceive you as an easily disgruntled employee. Try to present yourself as someone who, like most people, occasionally gets annoyed by certain situations, but doesn''t lash out in an outburst of anger.', 10),
(30, 'When I''m on a tight deadline and working to finish a project, I get frustrated if I run into roadblocks, like if my Internet won''t load. I realized it''s my fault for not preparing properly. I learned to be ready for worst case scenarios.', 75, '<b>Confession and recovery</b><br>\r\nMost valued answer should contain two components: first a description of the situation that angered you, and then a reference to how you processed the event and handled your anger.', 10),
(31, 'I tend not to dwell in the past and I''ll rather focus on the future job. There is not much that I''ll miss from my last job.', 25, '<b>Keep your answer positive</b><br>\r\nYou do not want to bring any negative issues into your answer. This is a great opportunity to express something positive about your character.', 11),
(32, 'I''ll sure miss the breakfast in the cafeteria  and the unlimited coffee in the office. We often received really nice presents from partners.', 50, '<b>Focus on the non-material.</b><br>\r\nResist the urge to all the material bonuses that came with the job as your primary pick. Focus on relations, knowledge, environment etc.', 11),
(33, 'Other from the great environment and amazing co-workers; I will definitely miss talking to clients in a friendly tone. I  hope I will have customers as good as then.', 75, '<b>This is where is gets amazing.</b><br>\r\nCarefully mention object of your to establish a clear connection between the previous job and the currently available position. For example, talking about missing the former co workers opens the door for expressing eagerness at the prospect of forging new professional relationships.<br>\r\nI know what you''re asking yourself and the answer is: Yes, there is always more than meets the eye in a job interview.', 11),
(34, 'I am absolutely certain I won''t miss that arrogant lady that works at help desk. She could totally ruin my day.', 25, '<b>Again - Keep It Positive!</b><br>\r\nI can''t stress enough that you avoid any negative experience with your previous employer.', 12),
(35, 'I''ll be honest I really did not like filling the order papers for office supplies Thank God you have a designated partner for that.', 50, '<b>Pick Things That Are Not a Priority</b><br>\r\nPick aspects of your past or current job that held the least interest to you. Make sure that any tasks you mention are not likely to be prioritized by your target employer, nor should they be frequently performed or highly important aspects of the position. ', 12),
(36, 'I certainly won''t miss that old 3PAR server my employer used. It was really buggy sometimes. Luckily for me you upgraded to Blade storage,  I''m sure it''s a beauty.', 75, '<b>Compare Your Job to the New Job</b><br>\r\nExamine the job you''re interviewing and notice the upgrades in the technology or workflow that your previous job did not implement. BONUS: Use this information to impress the interviewer.', 12),
(37, 'I don''t think me and my manager were getting along. He always tend to pick on me the most and give me the hardest tasks. He got really angry after I complained to his boss.', 25, '<b>Forget about your emotions</b><br>\r\nAn emotional answer can backfire and reflect poorly on you. It is far better to look at past situations objectively and analyze what needed to be solved and the outcome. Think about what you dealt with from a business perspective, not a personal one.', 13),
(38, 'I had a manager I didn''t get along with early in my career. Because of that experience, today I always make it a point to find common ground with anyone I work with and ask questions immediately if I need to clarify something.', 50, '<b>Site a specific example.</b><br>\r\nKeep your answer short and concise. Remember not to go into too many details. You are there to analyze the situation professionally. Spilling irrelevant details can cause negative language to seep into your answer.', 13),
(39, 'I had a rocky start with a manager once, because we had different expectations for the flow of the workday. Once we talked about it, we realized that our goals were very compatible, and we were able to work very successfully together for several years.', 75, '<b>Focus on positive results.</b><br>\r\nMake sure to limit your responses to situations where you took positive action that ended with a positive result. You can use buzzwords in these types of question such as respect, solution, identify, listen, resolve, and so on.', 13),
(40, 'Unlike my previous boss;  my dream boss would be someone who allows you the freedom to do your job with minimal supervision', 25, '<b>Never, under any circumstances, should you criticize a past supervisor.</b><br>\r\nYour prospective employer will likely assume you are a difficult employee and side with your former employer.', 14),
(41, 'The only thing that matters to me is that he treats people at all levels with courtesy and respect.\r\nI appreciate diversity in people so I will accept all kinds of people as long as there is mutual respect.', 50, '<b>Emphasize your adaptability </b><br>\r\nby sharing how you have thrived with a variety of supervisory styles in your past. Be prepared to give examples of how you have been productive with different types of bosses. ', 14),
(42, 'I always imagined my ideal boss to be respectful, even-tempered, knowledgeable, and professional. These are the values that are important to you so it''s important for your boss to have these as well.', 75, '<b>Show that you have character. </b><br>\r\nIt''s okay to say things such as you want a boss that you can respect and respects you back. You don''t want to come across as a pushover who lets people walk all over you. So you can list out some of your positive characteristics which your ideal boss would also share.', 14),
(43, 'The company hired a new Executive VP and he decided he wanted to bring in his own people from his previous organization.  I was really depressed, it took me a while to get back to my feet.', 25, '<b>Keep it positive when talking about why you left your job before the gap.</b><br>\r\nExplanations that scream: "I didn''t like my previous employer" don''t look good. Hiring managers might just ask why you didn''t wait to find a new job before quitting your old one, especially because it''s easier to find a new job when you''re already working.', 15),
(44, 'The company was forced to make budget cuts and lay off two from the department - unfortunately, I was the last member of the team they hired . However, I''m proud of the work that I did at Company X and can provide a positive recommendation from my former manager.', 50, '<b>Be Confident</b><br>\r\nWhile the thought of discussing how you came to be unemployed, especially if you were let go or fired, might make you uneasy, don''t panic. Resume gaps are not as uncommon as job seekers might think, show that you survived this period and are now stronger.', 15),
(45, 'After most of the company had been outsourced  I took some time before searching for another job.  I had enough funds on my account and I wanted to fill the gaps in my knowledge by taking some courses my busy schedule  would not allow. ', 75, '<b>Emphasize any activities you undertook during the gap to improve your professional standing.</b><br>\r\nThis is a huge one. Make sure to mention:<br>\r\n<ul>\r\n<li>Any certifications or courses you''ve done during the gap.</li>\r\n<li>Any consulting, freelance or contract work you''ve done. Consulting is a huge sign that you''ve taken your career in your hands. However, it''s not just enough to say you''re a consultant. New employers will want to know about what actual consulting work you did in the interim.</li>\r\n<li>Any other valuable experiences, for example volunteers or major personal projects.\r\nIf you were in fact dismissed from a previous job for some individual reason, unfortunately there''s nothing to do except wait to explain it in an interview. Just make sure you have a good explanation to provide in the interview.\r\n</li>\r\n</ul>', 15),
(46, 'I have done my research  and I believe that $1500 would suffice considering my skills and experience. ', 25, '<b>Give a number.</b><br>\r\nAvoid this as much as you can, this should not be your primary answer. Give a number only if they insist on it, but be sure you researched salaries for this position. It is also better to go under than above with the number.', 16),
(47, 'I understand that positions similar to this one pay in the range of $1000 to $1200 in our region. Something in that range would be acceptable.', 50, '<b>Give a range.</b><br>\r\nThis should be your answer if they are not happy with you being unspecific.  be sure to name a lower number that you''d be comfortable with, since that''s probably where the hiring manager will start your offer.', 16),
(48, 'I am sure if you pick me as the best candidate for the job I have no doubt we can agree on a fair number.', 75, '<b>Don''t answer.</b><br>\r\nThere are ways to get around this question, if you really don''t want to give a number right off the bat. One good tactic is to say that you want to learn more about the job first, before you think about the salary that would go with it. Except the employer to push you into giving the number. Just move to lower scored answer.', 16),
(49, 'Well, I guess because I''m smart and I work hard and I''m absolutely willing to do whatever you need and I love everything I''m going to do here and really want to be a part of this company.', 25, '<b>Don''t seem desperate nor overconfident.</b><br>\r\nEnough with the desperation! Also avoid false modesty or being too self-deprecating. If you applied for this job then you must have a value that employer wants to hear about.', 17),
(50, 'As you can see by my resume, the majority of my employment history has been as a construction manager, a role which has given me a good understanding of how regulated businesses, including banks, work. I am certain you can benefit from someone with that skills. ', 50, '<b>"Tailor" Your Answer</b><br>\r\nEvery organization has a specific set of Qualities that the potential hire needs to have in order to be successful in the position.  It''s up to you to demonstrate that you have these Qualities, and the most important place to do this is in your answers to the interview questions!', 17),
(51, 'When I read the job posting I noticed that you specifically mentioned you were looking for someone with project management experience. As you can see on my resume I have over 10 years of experience as a project manager, but what I think really sets me apart from other candidates.', 75, '<b>Focus on your Uniqueness</b><br>\r\nThe interviewer wants to know how you stand out amongst the other applicants. Therefore, focus on one or two qualities you possess that might be unique, or more difficult to find, in other interviewees. For example, if you are very experienced with a certain skill that the job requires, say so.', 17),
(52, 'Because I know I can make a really good contribution and your benefits are more than attractive.', 25, '<b>It''s Not About You</b><br>\r\nDon''t focus on the benefit to you of the job. While the employer probably wants you to be happy in the job, they don''t care about the benefit to you at this point. They want to know the benefit to them if they hire you.', 18),
(53, 'This company is internationally known for its products, and my experience in marketing has me intrigued by the opportunity this position presents.', 50, '<b>Know the Position and the Department (if possible)</b><br>\r\nGet to know the company you will be talking to. When you know details about them, their culture, their goals, their products, and their challenges, you are then able to talk about yourself and your fit into the company.', 18),
(54, 'It would be a great honor to work in a reputed company like yours. I get a chance to work between the skilled people this will help me to test my knowledge and skills and to know self ability.', 75, '<b>Compare Your Goals to the Job</b><br>\r\nOnce you have done all your pre-interview homework, you will never again find yourself blundering on critical questions like this. Instead, you will be prepared to talk knowledgeably about the company and position, why they interest you, and how you will fit in with your skill set, personality, and experience.', 18),
(55, 'I plan to be a VP at a major firm with at least 7 direct reports, a company car, and a salary of 150K (plus options of course). It will be hard but I''m ready for the challenge.', 25, '<b>Don''t be too specific.</b><br>\r\nAmbition is good. Goals are good. However, if you are too specific, you run the risk of stating goals that are not realistically achievable in the job available. From the interviewer''s perspective, that means you''re not a good fit.', 19),
(56, 'I see myself as a top performing employee in a well-established organization, like this one. I plan on enhancing my skills and continuing my involvement in (related) professional associations.', 50, '<b>Start With Your Interest in This Job</b><br>\r\nIt is often advantageous to emphasize your interest in thoroughly mastering the initial position before moving on. If it seems like you are rushing past that first job, employers might question how motivated you are to carry out those duties.', 19),
(57, 'Once I gain additional experience from this position, I would like to move on from a technical position to development department. Some of the most innovative thinkers in the industry work here and that''s a big reason why I would love to build a career here.', 75, '<b>Moving Up the Career Ladder</b><br>\r\nThere are a few jobs where you are expected to move on after a couple of years, including some analyst positions in investment banking and consulting, as well as legal assistants and scientific research assistants (for new college grads).', 19),
(58, 'I am currently not applying in any other companies. This position was my primary and most attractive choice.', 25, '<b>Be Careful What You Disclose</b><br>\r\nIn general, it''s a good idea to avoid stating that this job is the only one you are considering. Your marketability can be brought into question if you are not attracting attention from other employers. Your leverage in salary negotiations will also be minimized.', 20),
(59, 'I am applying for several positions with IT consulting firms where I can analyze client needs and translate them to development teams in order to find solutions to technology problems.', 50, '<b>Exploring Options</b><br>\r\nOften the best approach is to mention that you are exploring a number of other similar options in the company''s industry. In this situation, the prospective employer will realize that they are competing with your current employer for your services.', 20),
(60, 'While I am seriously exploring other positions where I can leverage my financial modeling skills, your position is a primary target for me', 75, '<b>Show Your Enthusiasm</b><br>\r\nBe sure to include an enthusiastic statement about how motivated you are to work with the organization in your answer. There is room here for you to elaborate on how you feel that you would be a valuable addition to their team.', 20),
(61, 'If I get the job when can I take time off for vacation?', 25, '<b>It''s better to just walk away than to ask strange questions.</b><br>\r\nThis is the part of the interview where you can pull out a joker out of your sleeve. Hiring manager has no influence on your questions. You can surprise him and gain additional value or just ruin yourself. Below is the list of question you should never ask.<br><br>\r\n\r\n<u><b>Questions you should not ask:</b></u><br>\r\nWhat''s the policy on dating co-workers?<br>\r\nWhat do you do at this company?<br>\r\nWhat is included in the benefits package?<br>\r\nDo you do background checks?<br>\r\nHow did I do?<br>\r\nWhat is your policy on drug use?<br>\r\nHow did I do?<br>\r\nNot asking questions at all.<br>', 21),
(62, 'Well, I gave great answers already. You gave me all the information I need. If I have any additional question can I contact you via email?', 50, '<b>Everything is clear thank you.</b><br>\r\nAlthough this is not a way to do it - it is still better than asking inappropriate question. Having no questions prepared sends the message that you have no independent thought process, or are ill-prepared, or are not bright, or some combination. Also, asking questions is a good way to dig into the company culture and the specific day-to-day responsibilities of the position, so that your first week in the position won''t be accompanied by any major surprises.<br></br>\r\n\r\n<u><b>Questions you can ask:</b></u><br>\r\nHow would you describe the responsibilities of the position?<br>\r\nHow would you describe a typical week/day in this position?<br>\r\nHow many people work in this office/department?<br>\r\nHow much travel is expected?<br>\r\nWhat are the prospects for growth and advancement?<br>\r\nWhat do you like about working here?<br>\r\nWhen can I expect to hear from you?<br>\r\nDo you have any reservations about my qualifications?<br>', 21),
(63, 'Who does this position report to? If I am offered the position, can I meet him/her?', 75, '<b>Prepare few questions to ask.</b><br>\r\nPrepare few intelligent, thoughtful and cordial questions. This particular answer is one of the high valued ones. Below is the list of more.<br></br>\r\n\r\n<u><b>High valued questions:</b></u><br>\r\nThese are some "high risk, high reward" questions. Don''t ask them if you aren''t confident that you can deliver the debate which comes after them.<br></br>\r\n<b>Tell me about the other members of your team.</b><br>\r\n<i>Then bring up how your portfolio of experiences and expertise helps round out the team, is complementary, or adds strength.</i><br>\r\n<br>\r\n<b>What do you envision my goals would look like for the first year?</b><br>\r\n<i>Come prepared! Share your own 30/60/90-day plan. Get at: how well do you know and appreciate this position?</i>\r\n<br><br>\r\n<b>If I were to have extraordinary success in the first six months of my tenure, what would be some examples of what I would have accomplished?</b><br>\r\n<i>Share previous examples from your work history where you have had easily-transferable successes.</i><br>\r\n<br>\r\n<b>What problems should I expect to encounter on the job in the short-term?</b><br>\r\n<i>Get at: where are the potential land mines: people, projects, politics, departments?</i><br>\r\n<br>\r\n<b>How does upper management view our department / division?</b><br>\r\n<i>Get at: is your work and/or department respected? Seen as valuable players? Catch the blame a lot?</i><br>\r\n<br>\r\n<b>What is the most significant project on your desk today?</b><br>\r\n<i>Ask this if you can think quickly on your feet. Provide insightful feedback on what''s shared. Clarify, brainstorm, show your worth and efficiency.</i>', 21),
(64, 'Delete', 25, 'Delete', 22),
(65, 'Delete', 50, 'Delete', 22),
(66, 'Delete', 75, '<b></b><br>', 22);

-- --------------------------------------------------------

--
-- Table structure for table `questions`
--

CREATE TABLE IF NOT EXISTS `questions` (
  `id` int(32) NOT NULL AUTO_INCREMENT,
  `question` varchar(256) COLLATE cp1250_croatian_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=cp1250 COLLATE=cp1250_croatian_ci COMMENT='Containt questions duh!' AUTO_INCREMENT=23 ;

--
-- Dumping data for table `questions`
--

INSERT INTO `questions` (`id`, `question`) VALUES
(1, 'Tell us about yourself.'),
(2, 'What is your greatest strength?'),
(3, 'What is your greatest weakness? '),
(4, 'What makes you the best candidate for this job?'),
(5, 'How does this job fit in with your career plan?'),
(6, 'How do you handle stress and pressure? '),
(7, 'What motivates you?'),
(8, 'What is the biggest criticism you received from your boss?'),
(9, 'What is your dream job? '),
(10, 'What makes you angry?'),
(11, 'What will you miss most about your last job?'),
(12, 'What won''t you miss about your last job?'),
(13, 'Have you ever had difficulty working with a manager?'),
(14, 'Describe your ideal boss.'),
(15, 'Describe the gap in your employment history.'),
(16, 'What are your salary expectations?'),
(17, 'Why should we hire you?'),
(18, 'Why do you want to work here? '),
(19, 'Where do you see yourself 5 years from now?'),
(20, 'Where else are you interviewing?'),
(21, 'Do you have any questions for us.');

-- --------------------------------------------------------

--
-- Table structure for table `tips`
--

CREATE TABLE IF NOT EXISTS `tips` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `question` varchar(512) COLLATE cp1250_croatian_ci NOT NULL,
  `tip` text COLLATE cp1250_croatian_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=cp1250 COLLATE=cp1250_croatian_ci AUTO_INCREMENT=15 ;

--
-- Dumping data for table `tips`
--

INSERT INTO `tips` (`id`, `question`, `tip`) VALUES
(1, 'How would you feel about working for a younger manager?', '<b>How to Respond</b><br>\r\nOne way to respond is to describe a profile of your ideal manager.  Base your profile on qualities like leadership ability, openness to new ideas, knowledge of cutting edge trends, communication skills and a track record of success in your industry. <br><br>\r\nAvoid mentioning the amount of experience your prospective manager possesses as a factor. Focus on the quality of his or her experience instead.   State definitively that age is not a relevant factor for you.\r\nRelate your interest in current trends in the industry, and ways in which you have been able to continue to grow and become more effective in your job through your association with your colleagues as well as managers. <br><br>\r\nTry to stress your belief that the ability to manage is not something that you feel is age related. A good manager has the knowledge and ability to bring out the best in their employees, regardless of their age or the age of their staff.\r\n'),
(2, 'What will you do if you don''t get this position?', '<b>How to Respond</b><br>\r\nExplain how you would take steps to improve yourself in order to put yourself in a better position next time. Here are sample interview answers which you can edit to fit your personal experiences and background: <br><br>\r\nI will continue looking in this field for another part time position that will fit my schedule and goals.\r\nI will consider broadening my search to include some different industries hiring part time people.\r\nI really feel like this would be a good fit for me, so I''m hoping I won''t have to think too much about that!'),
(3, 'What would you do if you found out the company was doing something illegal?', '<b>How to Respond</b><br>\r\nInterviewers ask questions about illegal and/or unethical company conduct to measure both ethics and company loyalty. The best answers will reflect a concern for ethics without sharing an overly zealous response which might jeopardize the reputation of the employer. <br><br>\r\nInterviewees can benefit by reflecting on an assumption that the incident may be isolated and not indicative of a companywide failure as they respond. <br><br>\r\n<b>Reporting Illegal or Unethical Actions</b><br>\r\nAsserting that you would bring the matter of illegality to your employer''s attention by following the chain of command is often the best approach. Typically, this would involve informing your supervisor of the suspected irregularity unless she was directly involved. In that case, you would go to your boss''s superior to report your concerns.\r\n'),
(4, 'What do you know about this company?', '<b>Spend a lot of time on their website, if they have one</b><br>\r\nLook for their mission & how they describe themselves\r\nCheck out staff and, if applicable, Board members\r\nLook for new programs, projects, new directions\r\nCheck out any press releases <br><br>\r\n<b>Use search engines to research the company & individuals</b><br>\r\nEspecially helpful if their website has little or no info\r\nSee if they''ve been in the news\r\nLook for magazine & newspaper articles\r\nLook for articles about key executives\r\nTry google.com/blog search for unexpected finds <br><br>\r\n<b>Look at Glassdoor and Indeed to see what employees say</b><br>\r\nNote: Disgruntled employees may be more likely to post\r\nPays to check this out anyway to see what you find. <br><br>\r\n<b>Use LinkedIn to search for the company / staff profiles</b><br>\r\nSee what they highlight. Again, look for any new directions. <br><br>\r\n<b>Use other social media to see what they''re saying</b><br>\r\nTwitter, Facebook, Google+\r\nAlso Pinterest, YouTube, Instagram'),
(5, 'Would you rather be liked or respected?', '<b>How to Respond</b><br>\r\nIn most work roles, being respected should be given greater emphasis, since it is typically linked more closely to competence and productivity. However, a significant factor to consider is the nature of your relationship with your colleagues. <br><br>\r\n<b>When to Focus on Respect</b><br>\r\nFor example, if you are interviewing for a managerial or executive role, you should certainly emphasize that being respected would be a priority for you, so that your employees will enthusiastically carry out your directives. <br>\r\nIt is important to add that although receiving respect from subordinates is necessary to a supervisory role, so too is giving respect. Make sure you express that you understand the reciprocal nature of professional and personal relationships.<br><br>\r\n<b>When to Focus on Being Liked</b><br>\r\nIn roles where teamwork and collegiality are important, you can reference your interest in being liked in order to create a harmonious work group. \r\nIf you are interviewing for a position that involves frequent contact with clients, in which a personable nature is required to establish rapport or maintain a positive relationship, then you should mention the benefit of being liked in regard to this component of you work. <br><br>\r\n\r\nYou will also need to deliver product information and solutions, so respect will also be important in order to inspire confidence in your customers. <br>\r\n<b>When to Mention Both</b><br><br>\r\nMost interviewers will accept a nuanced answer in which you mention the value of both being respected and liked.  However, you should be prepared to discuss the relative importance of one or the other if pressed.\r\n'),
(6, 'Do you prefer to work independently or on a team?', '<b>If you answer: <i>"Work on a team."</i> </b><br>\r\nThis seems like the obvious answer. After all, collaboration is a key part of a successful team, and you would assume that your boss wants to make sure that you can work well with your other coworkers. They don''t want someone who is going to be antisocial or disruptive during meetings, you reason. Thing is, the hiring manager may construe this as a sign that you need other people''s input, advice, and help to get your own work done. <br><br>\r\n<b>If you answer: <i>"Work alone."</i> </b><br>\r\nEven if you prefer to work by yourself, you might be hesitant to say so during the interview. By picking this option, you imagine that your boss-to-be is thinking that you''ll be holed up in your cubicle, unfriendly and unwilling to participate with your fellow colleagues. By opting for this choice, you might think that you are sending a message that you don''t like people and would prefer to work alone. Or, on the flip-side, you might answer this way to show that you can self-manage and get the job done without a lot of hand-holding or support. <br><br>\r\n<b>How you should answer: </b><br>\r\nOne good way to answer this question is to incorporate the positive aspects of both options. You can say something like, <br><i>"I enjoy both. My answer is both work on a team, and work alone. Depending on the project that needs to be done, I can work independently to complete my tasks on time, but I also enjoy brainstorming and collaborating with my colleagues."</i><br> That way, your potential boss realizes that you like a team environment, but you can also work independently as well.\r\n'),
(7, 'What type of work environment do you prefer?', '<b>How to Respond</b><br>\r\nThe key to answering questions about your work environment is to simply ensure that what you say is a part of the company. For example, you do not want to say "I like a relaxed work environment" if the company considers itself fast paced; and here''s a tip â€“ all companies consider themselves fast pace. Really, you should simply "prefer" a work environment that you know the interviewer will appreciate. There is no reason to confuse the interviewer with anything too complicated. <br><br>\r\n<b>Bad Answer</b><br>\r\n<i>"I prefer a low stress work environment, where managers and staff have a mutual respect for one another. I also like it when managers praise the employees, and no one is blamed for things they didn''t do."</i> <br>\r\nYou do not want any answer that requires the business be perfect either. For example, "I prefer an organized work environment" is a bad answer, because although the company may consider itself organized, they will also wonder if you can handle disorganization. <br><br>\r\n<b>Good Answer</b><br>\r\n<i>"My ideal work environment is one that is adaptive. When necessary, it easily handles fast paced work, and is ready for any challenges it undertakes, but also slows down when work is slow, recognizing the natural shifts in business and responding accordingly."</i>\r\n'),
(8, 'How do you evaluate success? ', '<b>How to Respond</b><br>\r\nIf success is the main goal for most employees, and it has to be (or at least this is what employers consider), than their view of success will affect their attitude towards their jobs and their behavior in the workplace. <br><br>\r\n\r\nDepending on the position you are applying for, in some cases success represents profit (for instance in sales); in other cases, it refers to professional development and social recognition; it may also be possible that success means feeling that you are contributing to the community (this may be the case of people working in non-profit organizations). <br>\r\nSo, in the case of this question, too, prior research about the company is vital. If the company has publicized its mission and goals, you will find it even easier to come up with a good answer.<br><br>\r\n\r\n<b>Let''s see a few examples of good answers to this question: </b><br>\r\n<i>"When I am at work, I evaluate success by the way I meet my superiors'' requirement and on how well I communicate with co-workers." <br><br>\r\n"For me, success means being an efficient part of the team. Success is not only about being able to work individually and achieving good results just on your own. Everyone needs to participate and work together." <br><br>\r\n"I determine success by assessing the outcome of my work. I focus on quantifiable results."</i>\r\n'),
(9, 'If you know your boss is 100% wrong about something how would you handle it?', '<b>How to Respond</b><br>\r\nThis is a question most people hate, however i feel it is a good question to be posed. It shows a lot about your character, and especially if the person who is interviewing you will be your boss, it may be best answered as personally as you feel. If you can relate this question to your current/previous boss that gives the interviewer the impression that not only are you a good judge of character, but also that you understand people are different and this situation may need approaching in a different way with a different boss, after all, how can you really say how you would deal with someone you don''t know yet? <br><br>\r\n\r\n<b>Example Answer</b><br>\r\n<i>"If I were sure my manager was wrong about something I would talk to them about it and discuss my thoughts, after all, my boss is human, and may not realize they have made an error. I would explain why I thought they were wrong, and what I thought was wrong. If we reached a deadlock I would suggest conferring with other colleagues about the issue. My present manager is very good at listening when I feel he is wrong about something, and if it comes to division we always resolve it by asking the rest of the team and the majority vote goes. We learn by the results who was right."</i>\r\n'),
(10, 'Which parts of this job are the most challenging for you?', '<b>How to Respond</b><br>\r\nOne way your interviewer might go about this is to figure out which aspects of the job will be the toughest for you to master. Some interviewers will ease into this topic by having you reflect on the most challenging components of the job.<br>\r\n<br><b>Best Answers</b><br>\r\nThe best way to approach this question is to analyze the job at hand and think about which components of the job will be most difficult for you, based on your past experiences.  You can start by breaking down the job into parts and thinking about the skills, knowledge and experiences you''ll need for each responsibility. You should also think about elements of the job that will require some learning or adjustment on your part.\r\n'),
(11, 'What were your expectations for the job and to what extent were they met?', '<b>How to Respond</b><br>\r\nThere isn''t a right or wrong answer to this question. The best way to respond is to discuss what you expected when you took the job and give examples of how the position worked out for you.\r\nIf the job wasn''t exactly what you expected, it''s fine to mention that. However, you should focus on the job itself, not the company, your boss, or your co-workers (if they were a problem). Do be careful how you answer and don''t focus too much on the negative.\r\n'),
(12, 'What are you passionate about?', '<b>How to Respond</b><br>\r\nYour response doesn''t need to be focused on work, but it should demonstrate your ability to devote yourself to a particular task or hobby about which you are passionate. <br><br>\r\n\r\nWhatever your response, provide some examples of how you have dedicated yourself to that interest or activity. You can also mention goals (such as training for a race, if running is your passion), which gives interviewers a sense of your long-term thinking and perseverance. <br><br>\r\n\r\nThe interviewer may ask follow-up questions about your passion, so make sure it''s something you feel comfortable discussing. If film is your passion, for instance, interviewers may ask for movie recommendations, or inquire about your favorite movie. <br><br>\r\n\r\nNo matter what you answer is, be sure that what you share isn''t something that could potentially cut into your working hours. <br><br>\r\n\r\nFor example, you don''t want to say that you''re a mountain climber with the goal of climbing Mountain Everest soon or that you''re getting ready for the Tour de France or looking to spend the winters skiing in Aspen.\r\n'),
(13, 'How would you adjust to working for a new company?', '<b>How to Respond</b><br>\r\nSince an employer is essentially assessing your adaptability, you need to convey how you have adjusted to new situations and demands in the workplace. <br> <br>\r\n\r\nTake an inventory of the transitions you have negotiated in the past.  Consider the variety of bosses for whom you have worked and their different supervisory and leadership styles.  If your workplace has retrenched, reorganized, merged or undergone any other challenges in the past, be ready to discuss how you dealt with those changes. <br> <br>\r\n\r\n<b>Be specific when describing how you adapted to a changing environment.</b><br>\r\nMention new skills you developed, adjustments made to your work style, or new strategies you applied to generate value for your employer. <br>\r\n\r\nYour answer can follow a relatively straightforward model: describe, using specifics, the challenges you faced; explain the action you took in response; and discuss the positive results you may have generated. <br> <br>\r\n\r\nIf it is true, you can also mention what about this particular company''s culture interests you, or makes you believe you will adapt well. For example, if you have heard that the company fosters a lot of teamwork and community, you can express your enthusiasm about becoming a part of that culture.\r\n'),
(14, ' How would you describe the pace at which you work?', '<b>How to Respond</b><br>\r\nWhen you''re asked to describe the pace at which you work, be careful how you respond. This is a question where faster isn''t necessarily better. Most employers would rather hire employees who work at a steady pace and produce quality results. Someone who is too slow to get the job done in a reasonable time frame isn''t going to be a good hire. Neither is a candidate who works frenetically all day because they might make more errors, or more easily burn out.<br>\r\n\r\n<br><b>Emphasize Steadiness and Quality</b><br>\r\nOne way to answer this question is to say that you work at a steady pace but usually complete work in advance of the deadline. You also want to emphasize that you achieve quality results at your pace. Provide a specific example of a time when working at this pace helped you achieve results.\r\n');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
